### PR TITLE
Rest

### PR DESCRIPTION
**Pull request by gpb01**
Enhancements in comments. Added sequential order to parameters.
Ignore macOS .DS_Store files.

### CODE REVIEW

**Comment by qniens** [comment]
Is this commit missing some files? I see CLIENT_TIMEOUT and the AUTH which are both new?

**Comment by SukkoPera** [comment]
No, it's for the development branch (namd *rest*).

**Comment by qniens** [comment]
You're correct. My bad.

**Comment by SukkoPera** [comment]
No problem. This branch will soon become v 0.9.1 and we'll need lots of testing :).

**Comment by qniens** [comment]
Sure! I've been using the library a lot.

**Comment by SukkoPera** [comment]
@qniens the 1.0rc was just released, see https://github.com/SukkoPera/Webbino/releases/tag/v0.9.95.

It would be great if you could please test it and report any issues you might find.

**Comment by qniens** [comment]
@SukkoPera Yes I saw the notifications popping up in my email. I will test it!

**Comment by qniens** [comment]
Hi @SukkoPera, I have updated the Webbino code v0.9.97 and it runs without major problems on a custom ATSAMD51G19A-MU board. This means it will run fine on every Adafruit SAMD51 / M4 board.

The only issue is the 
`return pgm_read_word (&(this -> length));`
in
FlashStorage.h

But I see the comments there that it is on the TODO list.

Also TAG replacement now runs on every file, instead on only html files. This is problematic for Jquery script using the $ sign. I suggest to use \` as the default tag delimiter. As this character is less frequent being used.

**Comment by SukkoPera** [comment]
Thanks a lot for your testing @qniens!

Tag replacement is only done for MIME types having `true` as the last parameter [here](https://github.com/SukkoPera/Webbino/blob/master/src/WebbinoCore/MimeTypes.h#L58). Do you think it would be better to disable it for `.js` files?

**Comment by qniens** [comment]
@SukkoPera Yes I think it is better to disable it by default for .js files. This will improve the initial user experience with the Webbino library. It took me awhile to find out why the minimized version of jQuery won't load. It was because of the TAG delimiter changing the source code of the js file.

In my setup I changed it to \` or \~. But both are also legit operators in JS.

I know the library is optimized for small memory MCU, but it works like a charm on faster IC like the SAMD51. I can make dynamic website(with the help of JQuery) like normal and just store it to FlashMemory.

**Comment by SukkoPera** [comment]
OK, done, thanks for the advice!

The problem with ` and ~ is that they are pretty hard to type on some non-English keyboards, Italian for instance (unless you are a Linux user :)). I'll leave it to $ but I'll add some words about it in the docs.

Thanks for all your help!

**Pull request merged**
